<?php


class equipmentModelModel {
	var $equipmentID;
	var $equipmentName;
	var $equipmentQuality;
	var $equipmentLevelMax;
	var $equipmentType;
	var $equipmentDescribe;
	var $killTarget;
	var $petTarget;
	var $petStrengthenProperty;
	var $heroStrengthenProperty;
	var $propTarget;
	var $propStrengthenProperty;
	var $skillType;
	var $skillEffectDescbribe;
	var $skillEffectNmuber;
	var $Time;
	var $NumberType;
	var $NumberTarget;
	var $Number;
	var $upNmuberAddType;
	var $upNumber;
	public static $data = array(
		1=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>0,
			'equipmentDescribe'=>'击杀敌方单位获得额外分数',
			'killTarget'=>0,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>0,
			'NumberTarget'=>0,
			'Number'=>10,
			'upNmuberAddType'=>0,
			'upNumber'=>2,
		),
		2=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>0,
			'equipmentDescribe'=>'击杀刺客型敌人额外获得分数',
			'killTarget'=>1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>0,
			'NumberTarget'=>0,
			'Number'=>100,
			'upNmuberAddType'=>0,
			'upNumber'=>10,
		),
		3=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>0,
			'equipmentDescribe'=>'击杀BOSS额外获得分数',
			'killTarget'=>2,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>0,
			'NumberTarget'=>0,
			'Number'=>2000,
			'upNmuberAddType'=>0,
			'upNumber'=>100,
		),
		4=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>1,
			'equipmentDescribe'=>'拾取金币时额外获得',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>0,
			'NumberTarget'=>1,
			'Number'=>10,
			'upNmuberAddType'=>0,
			'upNumber'=>1,
		),
		5=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>2,
			'equipmentDescribe'=>'关卡结算时获得额外百分比的经验',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>1,
			'NumberTarget'=>2,
			'Number'=>0.05,
			'upNmuberAddType'=>1,
			'upNumber'=>0.005,
		),
		6=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>2,
			'equipmentDescribe'=>'关卡结算获得的分数增加',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>1,
			'NumberTarget'=>0,
			'Number'=>0.01,
			'upNmuberAddType'=>1,
			'upNumber'=>0.02,
		),
		7=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>2,
			'equipmentDescribe'=>'关卡结算时获得额外的金币奖励',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>1,
			'NumberTarget'=>1,
			'Number'=>0.03,
			'upNmuberAddType'=>1,
			'upNumber'=>0.01,
		),
		8=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>3,
			'equipmentDescribe'=>'法阵的效果增强',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>1,
			'NumberTarget'=>3,
			'Number'=>0.1,
			'upNmuberAddType'=>1,
			'upNumber'=>0.02,
		),
		9=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>4,
			'equipmentLevelMax'=>60,
			'equipmentType'=>3,
			'equipmentDescribe'=>'法阵的有效范围增加',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>0,
			'NumberTarget'=>4,
			'Number'=>1,
			'upNmuberAddType'=>1,
			'upNumber'=>0.2,
		),
		10=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>4,
			'equipmentDescribe'=>'角色的法力上限增加',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>0,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>0,
			'NumberTarget'=>6,
			'Number'=>20,
			'upNmuberAddType'=>0,
			'upNumber'=>2,
		),
		11=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>5,
			'equipmentDescribe'=>'火系宠物的生命值增加',
			'killTarget'=>-1,
			'petTarget'=>1,
			'petStrengthenProperty'=>0,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>1,
			'NumberTarget'=>5,
			'Number'=>0.05,
			'upNmuberAddType'=>1,
			'upNumber'=>0.01,
		),
		12=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>6,
			'equipmentDescribe'=>'蓝瓶的恢复效果增强',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>1,
			'propStrengthenProperty'=>0,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>1,
			'NumberTarget'=>8,
			'Number'=>0.1,
			'upNmuberAddType'=>1,
			'upNumber'=>0.01,
		),
		13=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>7,
			'equipmentDescribe'=>'购买时间时获得额外的时间',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>-1,
			'skillEffectDescbribe'=>'',
			'skillEffectNmuber'=>0,
			'Time'=>-1,
			'NumberType'=>0,
			'NumberTarget'=>10,
			'Number'=>1,
			'upNmuberAddType'=>0,
			'upNumber'=>0.5,
		),
		14=>array(
			'equipmentName'=>'',
			'equipmentQuality'=>0,
			'equipmentLevelMax'=>15,
			'equipmentType'=>8,
			'equipmentDescribe'=>'召唤宠物时有概率额外获得X只宠物',
			'killTarget'=>-1,
			'petTarget'=>-1,
			'petStrengthenProperty'=>-1,
			'heroStrengthenProperty'=>-1,
			'propTarget'=>-1,
			'propStrengthenProperty'=>-1,
			'skillType'=>0,
			'skillEffectDescbribe'=>'召唤时获得额外X只宠物',
			'skillEffectNmuber'=>1,
			'Time'=>-1,
			'NumberType'=>1,
			'NumberTarget'=>9,
			'Number'=>0.05,
			'upNmuberAddType'=>1,
			'upNumber'=>0.01,
		),
	);

	function __construct($id) {
		$this->equipmentID = $id;
		$this->equipmentName = self::$data[$id]['equipmentName'];
		$this->equipmentQuality = self::$data[$id]['equipmentQuality'];
		$this->equipmentLevelMax = self::$data[$id]['equipmentLevelMax'];
		$this->equipmentType = self::$data[$id]['equipmentType'];
		$this->equipmentDescribe = self::$data[$id]['equipmentDescribe'];
		$this->killTarget = self::$data[$id]['killTarget'];
		$this->petTarget = self::$data[$id]['petTarget'];
		$this->petStrengthenProperty = self::$data[$id]['petStrengthenProperty'];
		$this->heroStrengthenProperty = self::$data[$id]['heroStrengthenProperty'];
		$this->propTarget = self::$data[$id]['propTarget'];
		$this->propStrengthenProperty = self::$data[$id]['propStrengthenProperty'];
		$this->skillType = self::$data[$id]['skillType'];
		$this->skillEffectDescbribe = self::$data[$id]['skillEffectDescbribe'];
		$this->skillEffectNmuber = self::$data[$id]['skillEffectNmuber'];
		$this->Time = self::$data[$id]['Time'];
		$this->NumberType = self::$data[$id]['NumberType'];
		$this->NumberTarget = self::$data[$id]['NumberTarget'];
		$this->Number = self::$data[$id]['Number'];
		$this->upNmuberAddType = self::$data[$id]['upNmuberAddType'];
		$this->upNumber = self::$data[$id]['upNumber'];
	}
}
